# Generated by Django 4.1.7 on 2023-03-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightmeasurement',
            old_name='date',
            new_name='measurement_date',
        ),
    ]
